name: .NET Core

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 1

      - name: Install SDK's
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            5.0.x
            3.1.x

      - name: NuGet cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
          
      - name: dotnet restore
        run: dotnet restore /p:Configuration=Release
      - name: dotnet pack
        run: dotnet pack --no-restore --configuration Release
      # - name: push build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: |
      #       **/*.*nupkg
      #     if-no-files-found: error

      - name: dotnet test
        run: |
          find ./test -type f -name "*Tests.csproj" -exec dotnet add "{}" package coverlet.msbuild \;
          dotnet test --no-restore --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="test/**/*.cs" --logger "trx;LogFilePrefix=testresults" --logger "console;verbosity=detailed"
      - name: Push test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/*.trx
            **/*.opencover.xml
          if-no-files-found: error
